### ISSUE TITLE
Update library

### ISSUE THREAD

**Issue by cpursley** [robconery/moebius#108]
This looks like a very useful library. Is there any interest in bringing it up to date?

I'm glad to help but not quite sure where to start. I get this after updating libs and running tests:

```
Generated moebius app
** (EXIT from #PID<0.93.0>) shutdown: failed to start child: TestDb
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function DBConnection.Poolboy.child_spec/1 is undefined (module DBConnection.Poolboy is not available)
            DBConnection.Poolboy.child_spec({Postgrex.Protocol, [username: "chase", types: Moebius.PostgrexTypes, name: TestDb, url: "postgres://localhost/meebuss", database: "meebuss", hostname: "localhost", pool: DBConnection.Poolboy]})
            (db_connection 2.4.1) lib/db_connection.ex:444: DBConnection.start_link/2
            (stdlib 3.16.1) supervisor.erl:414: :supervisor.do_start_child_i/3
            (stdlib 3.16.1) supervisor.erl:400: :supervisor.do_start_child/2
            (stdlib 3.16.1) supervisor.erl:384: anonymous fn/3 in :supervisor.start_children/2
            (stdlib 3.16.1) supervisor.erl:1242: :supervisor.children_map/4
            (stdlib 3.16.1) supervisor.erl:350: :supervisor.init_children/2
            (stdlib 3.16.1) gen_server.erl:423: :gen_server.init_it/2
```

**Comment by cpursley** [comment]
Actually, I think I figured it out. I'll work on this a bit and submit a PR.

**Comment by robconery** [comment]
Hi Chase - thanks so much! One of the major problems I was having was that the Elixir core team, who also owns Postgrex, decided they needed to keep tweaking Postgrex to work best with Ecto and Phoenix so they've kept the version < 1.0 and introduce breaking changes from time to time. In fact, after all these years, the driver is still at 0.16.

This broke Moebius every now and again - specifically the way dates were handled. In short it's just too much work and, if I'm honest, I don't think it's good for the ecosystem to have that much control within the core team.

I started a branch for 3.0 using Ecto and it was coming along and then I got distracted. So that's where we are. I have a ton of respect for José et al, but I (somewhat selfishly) don't agree with keeping the driver as malleable as they are.

**Comment by cpursley** [comment]
It does seem like Postgrex and the date stuff is more stable these days ~ but yeah, breaking changes are annoying.

I submitted a PR request with a few changes to get it working on the latest Elixir. The biggest change was replacing Poison with Jason, which required hanlding Structs differently (maybe there's a better way, but specs pass).

https://github.com/robconery/moebius/pull/109

I also plan to submit some other PRs adding features. Mainly, additional filter operators and the ability to configure multiple Postgrex Types (I need to be able to handle uuids and geo types).

**Comment by cpursley** [comment]
Ah, I just noticed the v4 branch (maybe that's what you meant when getting distracted instead of v3). Maybe I should be working off of v4?

**Comment by robconery** [comment]
If you want; there are some things I never ironed out (like transactions)
