### ISSUE TITLE
Support for other database engines?

### ISSUE THREAD

**Issue by mattweldon** [robconery/moebius#29]
Are there any plans to open Moebius up to other DB engines / drivers? 

I've [just started](https://github.com/mattweldon/exql) a project (heavily influenced by what you're doing here) to wrap the [TDS driver](https://github.com/livehelpnow/tds). Would my time be better spent looking into creating an adapter for Moebius instead?

Would be great to hear your thoughts!

**Comment by robconery** [comment]
That's kind of you thanks for asking :). Right now we're focusing almost exclusively on Postgres and the reason is that when you start abstracting the DB you water down what's capable. For instance JSONB support and `tsvector` stuff.

Anyway - which DB did you have in mind? Our API is pretty simple so if there's a way to do it easily without compromising functionality I might be open to it :).

**Comment by mattweldon** [comment]
Completely understand - thought that might be the case :)

I'm working on Exql for a project that interacts with a legacy MSSQL DB right now, so that's where I was planning on starting.

It might be too early to get something nailed on without muddying the waters for first-class PG support, but if you're open to it I'll take a look at where an abstraction _could_ fit and send it over for review? Feel free to park it since it's not really on the radar for the immediate future though :)

Thanks for the work so far :+1:
